Feat/#1 - p1 기능
pknu-wap/WABI-BE pull request #2
Opened 2024-08-30 07:44 UTC by JONG-KYEONG

##  📌 관련 이슈

- closed: #1 

## ✨ PR 세부 내용

### PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가 ✨
- [ ] 기능 삭제 🔥
- [ ] 버그 수정 🐛
- [ ] 코드 형태 개선 🎨
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트 🔨

### 변경 사항

1.  Qr 체크인  /api/check-in
     - QrController
     - QrService
     - QrRepository
     - Qr 체크인 관련 DTO
2.  체크인 명단  /api/events/{eventId} 
     체크인 상태  /api/events/{eventId}/status
     - EventController
     - EventService
     - EventRepository
     - 이벤트 관련 DTO
3.  그룹 학생 명단 보기  /api/bands/{bandId}/students
     - BandController
     - BandService
     - Band 관련  Repository
4.  신규 인원 자동 추가   /api/bands/{groupId}/members/enrollments/file, 
     신규 인원 수동 추가   /api/bands/{groupId}/members/enrollments/manual
     - BandEnrollController
     - BandEnrollService
     - FileToBandStudentTranslator

### 이슈 사항

1. csv, xlsx 파일 업로드
   
   ![image](https://github.com/user-attachments/assets/5d1e5b76-e9b3-4012-9d0f-30bd44b47f68)
   ![image](https://github.com/user-attachments/assets/ca79f55c-9f26-4a9e-85c8-18cdbe26b76f)
   csv 파일은 openCSV 라이브러리 사용하여 저장, xlsx, xls 파일의 경우 Apache POI 라이브러리 사용하여 저장

2. xlsx, xls 파일 주의사항

    엑셀 파일은 셀 마다 아래의 데이터 타입이 있어서 타입 변환을 해주어야한다.
    - STRING
    - NUMERIC
    - BOOLEAN
    - FORMULA

   따라서 각 셀들을 String 으로 변환 해주는 메소드를 추가로 작성하여 사용해주었다.

   ![image](https://github.com/user-attachments/assets/41d375d7-a909-4aaf-9ac9-30917aacdba3)

3. 엑셀 파일 지수 표기법 문제

    ![image](https://github.com/user-attachments/assets/3ae7fb43-8e77-4f84-877a-2f34bd4f8a06)

    엑셀에서 숫자가 너무 길거나 셀의 너비가 좁을 경우, 자동으로 지수 표기법으로 표시될 수 있다. 

    Apache POI를 사용할 때 지수 표기법 대신 원래의 숫자 형태를 사용하기 위해 위와 같이 toBigDecimal( ) 함수를 사용하여 변환해주어야한다.

4. FileToBandSudentTranslator

    ![image](https://github.com/user-attachments/assets/4446ede9-d1de-41d0-81f3-1e5b371877e7)

    파일 업로드 방식의 그룹 명단 등록의 경우, 파일에서 데이터를 뽑고 난 후 부터의 로직은 수동 업로드 방식과 동일하다.
    그래서 FileToBandSudentTranslator 클래스에서 파일 -> 데이터 추출 후 수동 업로드의 메소드를 그대로 사용할 수 있게 구성하였다.

6. 예외 처리
    - exception
    - ErrorCode
        - error코드와 해당하는 메시지를 요구사항에 맞게 적용한다.
    - GlobalExceptionHandler
        - `@ExceptionHandler(RestApiException::class)`
            - RestApiException생성자로 예외를 생성하고 던지면 GlobalExceptionHandler에서 해당 예외를 처리한다.
        - 직접 정의한 ErrorCode 사용해 에러 메시지를 정의할 수 있다.
    - RestApiException
        - RuntimeException을 상속받아 예외를 처리하기위한 클래스이다.

### 참고사항
p1 기능 개발을 위한 엔티티 구현이 하나의 브랜치에 묶이다보니 pr이 비대해진 점 양해 부탁드립니다.

2024-08-30 15:41 UTC, seokjin8678 requested changes
고생하셨습니다!

우선 Code Style부터 통일할 필요가 있어 보이네요 😂

또한 Serivice 레이어에 공통적으로 누락된 어노테이션이 있는 것 같습니다.

그리고 DB 테이블을 정의한 DDL 있으시다면 따로 노션에 작성해주세요..!

2024-08-30 15:41 UTC, seokjin8678 commented on wabi/build.gradle.kts
> +    implementation("mysql:mysql-connector-java:8.0.26")
`runtimeOnly("org.mariadb.jdbc:mariadb-java-client")`
`runtimeOnly("com.mysql:mysql-connector-j")`
`implementation("mysql:mysql-connector-java:8.0.26")` 

각 라이브러리를 추가한 이유가 있으실까요?
있다면 해당 라이브러리를 어떠한 이유로 추가하셨나요?

2024-08-30 15:41 UTC, seokjin8678 commented on wabi/build.gradle.kts
>      testRuntimeOnly("org.junit.platform:junit-platform-launcher")
마찬가지로, 해당 라이브러리를 어떠한 이유로 추가하셨나요?

2024-08-30 15:41 UTC, seokjin8678 commented on wabi/build.gradle.kts
> +    }
![image](https://github.com/user-attachments/assets/bdc48013-51ee-45fa-b0e7-8ceddc29635c)
해당 줄의 마지막에 있는 빨간색 아이콘은 무엇을 의미하는 것일까요?
hint: EOL

2024-08-30 15:41 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/controller/BandController.kt
> +    }
```suggestion
    fun getBandStudents(@PathVariable bandId: Long) : ResponseEntity<Response> {
        return ResponseEntity(bandService.getBandStudents(bandId = bandId), HttpStatus.OK)
    }
```
IntelliJ Settings의 Editor -> Code Style에서 Scheme 형식을 통일할 필요가 있어 보이네요!

2024-08-30 15:41 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/entity/Band.java
> +    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
마찬가지로 코드 스타일 통일이 필요해 보입니다..!
```java
@Entity
public class BandStudent {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    ...
```

2024-08-30 15:41 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/payload/BandStudentDto.kt
> +package com.wap.wabi.band.payload
payload라는 패키지명은 어떠한 이유로 이름을 정하셨나요?

2024-08-30 15:41 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/entity/BandStudent.java
> +    }
접근자가 public인 매개변수가 없는 생성자를 만드신 이유가 이유가 있나요?

2024-08-30 15:41 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/qr/controller/QrController.kt
> +}
API 명세서에서 적은 URL과 해당 컨트롤러에서 정의한 URL이 맞나요?

2024-08-30 15:41 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/qr/controller/QrController.kt
> +package com.wap.wabi.qr.controller
qr이라는 패키지 이름이 추후 다른 사람이 보았을 때 무슨 역할을 하는지 쉽게 알 수 있을까요?

2024-08-30 15:41 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/exception/GlobalExceptionHandler.kt
> +}
지금은 예외가 발생하면 무조건 500 에러를 반환하는데, 백엔드에서 500 에러를 발생해야 할 상황은 어떤 상황이라고 생각하시나요?

2024-08-30 15:41 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/exception/GlobalExceptionHandler.kt
> +            .body(Response(errorCode.code.toString(), errorCode.message.toString(), ""))
마지막에 `""` 문자열을 넣는 이유는 무엇인가요?

2024-08-30 15:41 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/exception/GlobalExceptionHandler.kt
> +            .body(Response(errorCode.code.toString(), errorCode.message.toString(), ""))
`errorCode.message`의 타입은 String인데 왜 `toString()`을 호출하나요?

2024-08-30 15:41 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/common/payload/response/Response.kt
> +    val data : Any
Any 타입을 사용한 이유가 있으실까요?

2024-08-30 15:41 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/event/entity/Event.java
> +}
https://stackoverflow.com/questions/4668218/are-there-any-java-method-ordering-conventions

2024-08-30 15:41 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/event/entity/EventBand.java
> +import jakarta.persistence.*;
https://stackoverflow.com/questions/147454/why-is-using-a-wild-card-with-a-java-import-statement-bad
https://google.github.io/styleguide/javaguide.html#s3.3.1-wildcard-imports

2024-08-30 15:41 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/service/FileToBandStudentTranslator.kt
> +    }
when 절에 `... == true`를 사용할 필요가 있을까요?
사용하지 않도록 하려면 어떤 방법을 사용하면 좋을까요?
hint: Elvis 연산자

2024-08-30 15:41 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/service/FileToBandStudentTranslator.kt
> +    }
`CSVReader`는 `Iterable` 인터페이스를 구현하는데도 불구하고 while loop를 사용한 이유가 있나요?

2024-08-30 15:41 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/event/entity/Enum/EventStudentStatus.java
> +}
Enum은 `,`로 구분했을 때 줄바꿈을 하는게 좋아요

2024-08-30 15:41 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/event/entity/Enum/EventStudentStatus.java
> +package com.wap.wabi.event.entity.Enum;
https://google.github.io/styleguide/javaguide.html#s5.2.1-package-names

2024-08-30 15:41 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandService.kt
> +    }
1. `@Transcational` 어노테이션을 사용하지 않은 이유가 있나요?
2. Service 클래스에서 API 응답에 의존적인 `Response`를 반환하는 이유가 있나요?

2024-08-30 15:41 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandService.kt
> +        val band = bandRepository.findById(bandId).orElseThrow{throw RestApiException(ErrorCode.BAD_REQUEST_BAND)}
코틀린을 사용하면서 Optional을 사용할 필요가 있을까요?

2024-08-30 15:41 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/exception/ErrorCode.kt
> +    BAD_REQUEST_BAND("400-1", "밴드Id를 확인해주세요."),
400과 404는 무슨 차이가 있나요?

2024-08-30 15:41 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/qr/repository/QrQueryDslRepository.java
> +}
해당 클래스가 어딘가에서 사용되고 있나요?

2024-08-30 15:41 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/qr/service/QrService.kt
> +        return Response("200", "체크인에 성공하였습니다. ", "")
줄바꿈을 어떤 의도로 하셨나요?

2024-08-30 15:41 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/qr/service/QrService.kt
> +        eventStudentRepository.save(eventStudent)
`save()` 메서드를 호출하는 이유가 있나요?

2024-08-30 15:41 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/qr/service/QrService.kt
> +        return Response("200", "체크인에 성공하였습니다. ", "")
마지막의 `""` 문자열은 무엇을 의미하나요?

2024-08-30 15:41 UTC, seokjin8678 commented on wabi/src/main/resources/application.properties
`application.properties`를 삭제하신 이유가 있나요?

2024-08-30 15:41 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/event/service/EventService.kt
> +
🫥

2024-08-30 15:47 UTC, seokjin8678 commented on wabi/build.gradle.kts
> +    kotlin("kapt") version "1.9.22"
+ 해당 플러그인은 어떠한 이유로 추가하셨나요?

2024-08-30 15:47 UTC, seokjin8678 commented on wabi/build.gradle.kts
> +    compileOnly("org.projectlombok:lombok")
코드를 보면 Lombok을 사용하는 곳이 없어보이네요!

2024-09-01 12:15 UTC, FhRh commented on wabi/build.gradle.kts
> +    kotlin("kapt") version "1.9.22"
kapt는 코틀린에서 자바의 어노테이션들을 사용할 수 있게 해주는 플러그인입니다. 여러모로 어노테이션을 사용할 일이 많아서 적용하게 되었습니다.

2024-09-01 12:23 UTC, FhRh commented on wabi/build.gradle.kts
>      testRuntimeOnly("org.junit.platform:junit-platform-launcher")
아직 어떤 DB를 사용할지 정해지지 않은 상태라서 각자 편한 DB에 연결해서 개발하기 위해 mariadb와 mysql 의존성 모두 추가하였습니다. 곧 배포 전략과 함께 사용할 DB를 정하게 되면 최적화할 생각입니다!

2024-09-01 12:35 UTC, FhRh commented on wabi/build.gradle.kts
> +    }
EOL이 End Of Line. 즉, 개행문자임을 알고 있었으나 왜 깃허브에서 EOL이 표기되는지는 몰랐기에 찾아보았습니다.
깃허브는 POSIX명세에 따라 파일마다 EOL을 요구합니다. 이를 위반할 시 파일을 구분하기 어렵거나 예기치 않은 동작이 발생할 수 있다고 하네요..
깃으로 파일을 푸시할때 나오는 CR/LF 경고문이 운영체제 마다 개행이 다르기 떄문임을 알고 있었으나, 왜 개행이 중요한지는 깊게 생각해본적이 없는데 다시 한번 생각해보게 되네요 :)

2024-09-01 13:23 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/band/entity/BandStudent.java
> +    }
jpa를 사용하기 위해 기본생성자를 만들어두었지만, 직접 setter를 정의 하지 않은 시점에서 해당 생성자가 public일 이유는 없어보이네요 수정하겠습니다!

2024-09-01 13:40 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/band/payload/BandStudentDto.kt
> +package com.wap.wabi.band.payload
payload는 dto와 같이 단순히 데이터를 전달하기 위한 목적을 가지고 json으로 변환될 가능성이 있는 객체들을 모아두는 패키지로, HTTP로 전송되는 데이터나 payload라고 부르기에, 패키지명으로 적합하다고 사용하게 되었습니다.

2024-09-01 13:45 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandService.kt
> +        val band = bandRepository.findById(bandId).orElseThrow{throw RestApiException(ErrorCode.BAD_REQUEST_BAND)}
보다시피 Service는 코틀린으로 작성되었지만, JPA를 사용함에 따라 Entity와 Repository가 자바로 작성되어 컬렉션이 아닌 객체는 기본적으로 Optional로 반환하게 됩니다.
물론, findById 같은 메서드의 경우도 null을 반환하게 할 수 있지만, jpa가 기본적으로 메서드를 제공함으로써 얻는 보일러플레이트 제거에 대한 이점을 얻지 못하게 되어 위와 같이 작성하였습니다.
코틀린의 null안정성과 jpa의 이점중 어떤 것을 고르는게 가장 큰 이득일지 여전히 고민되네요..

2024-09-01 13:52 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandService.kt
> +    }
1. 사용하지 않은 이유가 따로 있는 것은 아니고, 간과한 부분인것 같습니다..
2. 곰곰히 생각해보니 이와 같은 반환 방식은 HTTP API 통신에 확실히 의존적인것 같아요! 팀원들과 상의한 후에 수정하도록 하겠습니다!

2024-09-01 13:53 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/common/payload/response/Response.kt
> +    val data : Any
Data로는 모든 객체가 올 수 있도록 Object를 사용하려 하였으나, 코틀린에서는 이를 Any타입으로 지정한다는 글을 보고 이와 같이 작성하였습니다.

2024-09-02 05:30 UTC, Due-IT commented on wabi/src/main/kotlin/com/wap/wabi/qr/controller/QrController.kt
> +package com.wap.wabi.qr.controller
기능 명세를 모르는 분들이 봤을때 qr이라는 이름만으로는 어떤 기능인지 쉽게 유추하기 어려울거 같네요 수정하겠습니다!

2024-09-02 05:48 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/event/entity/Event.java
> +}
좋은 자료네요 얌냠냠

2024-09-02 05:55 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/event/entity/EventBand.java
> +import jakarta.persistence.*;
구글에선 와일드카드를 사용한 import를 하지 않는 군요.
이유가 궁금해서 찾아보았는데, 컴파일 시간을 줄이는 이점도 있지만 가독성에도 영향을 미치는 것 같네요.
인텔리제이에서는 같은 패키지의 import가 5개가 넘어가면 자동으로 와일드카드로 변환한다고 하는데, 이렇게 자동적으로 설정된 부분을 구글에서 일일이 와일드카드를 풀어가며 사용할거 같진 않고 5개 이상의 import를 사용하지 않도록 패키징 분리에 대해 조금 더 공부해야겠다는 생각이 드네요

2024-09-02 05:58 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/exception/ErrorCode.kt
> +    BAD_REQUEST_BAND("400-1", "밴드Id를 확인해주세요."),
저도 조금 헷갈리는 부분이었어서 이번 기회에 찾아보았습니다.

![image](https://github.com/user-attachments/assets/4d2dcdda-82d9-4803-84b1-3760c1344ca0)
위의 예시에 따르면, 400번대에서 404번대로 넘어가야할 에러들이 몇몇 보이네요.

2024-09-02 06:02 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/exception/GlobalExceptionHandler.kt
> +            .body(Response(errorCode.code.toString(), errorCode.message.toString(), ""))
빈값을 나타내려 하였으나, 굳이 빈문자열이 아니고 null이어도 괜찮을것 같아요

2024-09-02 06:03 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/exception/GlobalExceptionHandler.kt
> +            .body(Response(errorCode.code.toString(), errorCode.message.toString(), ""))
그러네요 인지하지 못하고 지나친것 같습니다..!

2024-09-02 06:06 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/qr/repository/QrQueryDslRepository.java
> +}
이번 프로젝트에서 복잡한 쿼리대신 queryDSL을 적용해보고 싶어 추가해두었으나, 공부하고 적용할 시간이 부족해서 아직 사용하고 있지 못하고 있어요. 우선은 제거해둬야 하겠네요..!

2024-09-02 06:07 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/qr/service/QrService.kt
> +        eventStudentRepository.save(eventStudent)
save가 있는게 보다 명시적일거 같아서 위와 같이 작성하였습니다..!

2024-09-02 06:12 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/qr/service/QrService.kt
> +        return Response("200", "체크인에 성공하였습니다. ", "")
해당 메서드의 기능을 설명하자면 아래와 같이 설명할 수 있을것 같아요.
1. 엔티티를 조회하고
2. 체크인 여부를 확인하고
  - 이미 체크인 되어 있다면 예외를
  - 체크인 되어 있지 않다면 체크인을 수행
3. 엔티티를 저장하고
4. 응답을 반환한다

저는 기능별로 줄바꿈을 수행하려는 편인데, 이번엔 잘 반영되지 못한것 같네요

2024-09-02 06:14 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/qr/service/QrService.kt
> +        return Response("200", "체크인에 성공하였습니다. ", "")
이도 빈 문자열보다는 null로 반환하는게 좋을것 같네요..

2024-09-02 06:26 UTC, FhRh commented on wabi/src/main/resources/application.properties
[https://github.com/pknu-wap/WABI-BE/commit/1dd10926bbbdd0c391e9845b18d4faa4d0d637d0](url)

위 커밋부터 application.properties가 삭제되었는데, 음.. 로컬 설정이지만 노출되는게 우려스러웠던거 같아요.
하지만, 이러면 이 오픈소스를 이용하려는 사람의 입장에서 온전히 실행되지 않는 서비스가 되어버릴 수 있겠네요

2024-09-02 06:32 UTC, SeongHoonC commented on wabi/src/main/kotlin/com/wap/wabi/qr/service/QrService.kt
> +        return Response("200", "체크인에 성공하였습니다. ", "")
arguments name 을 표시하면 명시적으로 어떤 값이 전달되는지 확인 가능합니다.

2024-09-02 09:43 UTC, FhRh commented on wabi/build.gradle.kts
> +    compileOnly("org.projectlombok:lombok")
제거 완료하였습니다 :)

2024-09-02 09:47 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/qr/controller/QrController.kt
> +}
API명세를 제대로 반영하지 못하였었네요.. 수정하였습니다!

2024-09-02 09:54 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/exception/GlobalExceptionHandler.kt
> +}
개인적으로 서버에서 500에러를 반환하는 경우는 프론트에서 문제를 해결할 수 없는 경우라고 생각합니다.
하지만, 지금은 로직의 문제가 아닌 경우에도 일관적으로 500에러를 뱉고 있네요. 다시 고려되어야할 부분인것 같습니다!

2024-09-02 13:08 UTC, seokjin8678 requested changes
코멘트에 답을 어느 정도 달아주셨고, 수정도 된 것이라 판단하여 추가 리뷰 남겼습니다.

남긴 리뷰에도 답변 달아주시면 될 것 같네요!

2024-09-02 13:08 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/student/entity/Student.java
> +}
엔티티는 식별자에 auto increment 값을 사용하지 않았네요!
만약 해당 엔티티를 `save` 하면 어떤 쿼리가 발생할까요?

2024-09-02 13:08 UTC, seokjin8678 commented on wabi/src/main/resources/application-prod.properties
> +spring.jpa.hibernate.ddl-auto=update
1. 운영 환경에서 `show-sql` 설정을 켜주셨는데, 어떤 이유에서 사용하셨나요? (반드시 비활성화 할 필요는 없습니다)
2. `ddl-auto`를 update로 설정하셨는데, 해당 설정을 하면 어떤 DDL이 발생하나요?

2024-09-02 13:08 UTC, seokjin8678 commented on wabi/src/main/resources/application-prod.properties
> +spring.datasource.password=${PASSWORD}
👍
운영 환경에 사용되는 계정과 관련된 환경 변수는 절대로 노출되지 않도록 관리 바랍니다..!

2024-09-02 13:08 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/entity/BandStudent.java
> +    private String academicStatus;
`academicStatus` Enum을 사용하지 않은 이유가 있나요?

2024-09-02 13:08 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/payload/response/BandStudentData.kt
> +        }
해당 메서드는 어디서 사용하나요? 외부에서 사용하지 않는 곳이 있다면 어떤 처리를 해줘야 할까요?

2024-09-02 13:08 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/payload/request/EnrollRequest.kt
> +data class EnrollRequest(val bandStudentDtos : List<BandStudentDto>)
해당 요청을 클라이언트가 보내려면 어떠한 JSON 포맷으로 요청을 보내야 할까요?

```json
{
  "채워주세요"
}
```

2024-09-02 13:08 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/payload/response/BandStudentData.kt
> +data class BandStudentData(
`BandStudentData`, `BandStudentDto`
여기서 Data와 Dto 접미사는 각 어떤 의미를 가지나요?
그리고 어느 곳에서 두 접미사가 사용되나요?

2024-09-02 13:08 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/repository/BandStudentRepository.java
> +public interface BandStudentRepository extends JpaRepository<BandStudent, Long> {
Repository 클래스에 `@Repository` 어노테이션이 붙은 곳이 있고 붙지 않은 곳이 있는데, 어떤 점에서 이를 구분하셨나요?

2024-09-02 13:08 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandEnrollService.kt
> +	}
해당 메서드는 어디서 사용하나요? 외부에서 사용하지 않는 곳이 있다면 어떤 처리를 해줘야 할까요?

2024-09-02 13:08 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandEnrollService.kt
> +				bandStudentDto.academicStatus
해당 필드는 모두 String 타입이네요!
그런데 만약 순서가 바뀐다면 무슨 일이 발생할 것 같나요?

2024-09-02 13:08 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandEnrollService.kt
> +		var bandStudents : MutableList<BandStudent> = mutableListOf()
var과 val 차이가 무엇인가요?

2024-09-02 13:08 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandEnrollService.kt
> +		request.bandStudentDtos.map { bandStudentDto ->
`map` 메서드는 어떤 동작을 하나요?

2024-09-02 13:08 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandEnrollService.kt
> +					bandStudentDto.club.toString(),
club은 String 타입인데, toString을 호출할 이유가 있을까요?
만약 있다면 null 값에 `toString`을 하면 어떤 문자열이 반환될까요?

2024-09-02 13:08 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandEnrollService.kt
> +		bandStudentRepository.saveAll(bandStudents)
`saveAll` 메서드를 호출하면 어떤 쿼리가 발생할까요?

2024-09-02 13:08 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandEnrollService.kt
> +		return if(student.isPresent) student.get() else studentRepository.save(Student(studentId, name))
`Optional`에는 다양한 메서드를 제공하는데, 그 중 하나로 간단하게 해결할 수 있을 것 같네요!

2024-09-02 13:08 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandService.kt
> +		val band = bandRepository.findById(bandId).orElseThrow { throw RestApiException(ErrorCode.NOT_FOUND_BAND) }
`orElseThrow` 메서드에는 매개변수로 무엇이 들어가야 하나요?

2024-09-02 13:08 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/event/controller/EventController.kt
> +        val response = Response.ok(data = null);
이와 비슷하게 data에 null을 할당하는 코드가 많다면 매번 `(data=null)`을 해줘야 할까요?

2024-09-02 13:08 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/event/repository/EventStudentRepository.java
> +}
1. Repository는 왜 코틀린으로 작성하지 않으셨나요?
2. 사용하지 않는 import가 보이네요!
3. `java.util.List`, `java.util.Optional`는 왜 중간에 공백으로 구분했나요?
4. Repository만 따로 메서드끼리 공백을 두지 않은 이유가 있나요?
5. `@Query` 내부에 있는 JPQL은 문자열 자동 포매팅 대상이 될까요?
6. Repository에서 주로 사용되는 접두사는 어떤게 있나요?

2024-09-02 13:08 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/event/service/EventService.kt
> +		val notCheckInCount = eventStudentRepository.getEventStudentStatusCount(event, EventStudentStatus.NOT_CHECK_IN.toString())
Enum을 그대로 사용하지 않은 이유가 있나요?

2024-09-02 13:08 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/event/service/EventService.kt
> +			.orElseThrow { throw RestApiException(ErrorCode.UNAUTHORIZED_CHECK_IN) }
`eventStudent`를 조회할 때, `student`와 `event`를 조회할 때의 장점이 무엇인가요?

2024-09-02 13:08 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/event/service/EventService.kt
> +		check(eventStudent.status.equals(EventStudentStatus.NOT_CHECK_IN)) { throw RestApiException(ErrorCode.ALREADY_CHECK_IN) }
`check()` 메서드는 어떤 예외를 반환하나요?
그리고 해당 예외가 던져지면 서버는 어떤 응답을 반환하나요?

2024-09-02 13:10 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/qr/service/QrService.kt
> +        eventStudentRepository.save(eventStudent)
JPA를 사용하면 명시적으로 update 쿼리를 날리지 않는데, 어떠한 이유 때문에 그럴까요?

2024-09-02 13:10 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/entity/BandStudent.java
> +    }
나머지 부분도 수정 부탁드립니다!

2024-09-02 13:11 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/qr/controller/QrController.kt
> +}
수정이 제대로 되었을까요..? 😂

2024-09-02 13:12 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/common/payload/response/Response.kt
> +    val data : Any
제네릭을 사용할 수 있지 않을까요?

2024-09-02 13:13 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/service/FileToBandStudentTranslator.kt
> +    }
```kotlin
val originalFilename = file.originalFilename ?: throw RestApiException(ErrorCode.BAD_REQUEST_FILE_TYPE)
return when {
    originalFilename.endsWith(".csv") -> processCsvFile(file)
    originalFilename.endsWith(".xlsx") || originalFilename.endsWith(".xls") -> processExcelFile(file)
    else -> throw RestApiException(ErrorCode.BAD_REQUEST_FILE_TYPE)
}
```
이렇게 사용할 수 있지 않을까요?

2024-09-02 13:14 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandService.kt
> +        val band = bandRepository.findById(bandId).orElseThrow{throw RestApiException(ErrorCode.BAD_REQUEST_BAND)}
`JpaRepository`를 사용했을 때 장점과 단점이 무엇이 있다고 생각하시나요?

2024-09-02 14:03 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/exception/ErrorCode.kt
> +enum class ErrorCode (val httpStatus : HttpStatus = HttpStatus.INTERNAL_SERVER_ERROR, val code: String = "", val message: String = ""){
해당 코드에 버그가 존재하네요.
해당 Enum이 어디서 사용된다면 무슨 일이 발생할까요?

2024-09-02 14:51 UTC, Zepelown commented on wabi/build.gradle.kts
> +    }
테스트

2024-09-02 14:52 UTC, Zepelown commented on wabi/build.gradle.kts
> +    implementation("mysql:mysql-connector-java:8.0.26")
테스트

2024-09-02 14:54 UTC, JONG-KYEONG commented on wabi/build.gradle.kts
> +    implementation("mysql:mysql-connector-java:8.0.26")
특별한 이유 없이 기존 프로젝트의 코드를 그대로 사용했었습니다.

진행 중인 프로젝트에 맞게 runtimeOnly("com.mysql:mysql-connector-j")  라이브러리만 남기고 제거하겠습니다!

2024-09-02 14:54 UTC, JONG-KYEONG commented on wabi/build.gradle.kts
> +    compileOnly("org.projectlombok:lombok")
코틀린에서 Lombok을 지원하지 않아서 제거해야하는데 놓쳤던 거 같습니다!
수정하도록 하겠습니다!

2024-09-02 14:54 UTC, JONG-KYEONG commented on wabi/build.gradle.kts
> +    }
찾아보니 파일의 마지막이 개행 문자로 마무리 되는 것이 아닌 문자로 마무리 되었다는 것을 알려주는 아이콘이라고 합니다.

'파일의 마지막에는 개행이 포함되어야 한다.' 라는 POSIX를 만족시키기 위함이라고 알게되었습니다.

아무 생각 없이 넘어갔던 부분이었는데, 새로운 부분을 공부할 수 있었습니다!

2024-09-02 14:54 UTC, JONG-KYEONG commented on wabi/src/main/kotlin/com/wap/wabi/band/service/FileToBandStudentTranslator.kt
> +    }
오호 이런게 있군요!
공부해서 적용해보겠습니다.

2024-09-02 14:54 UTC, JONG-KYEONG commented on wabi/src/main/kotlin/com/wap/wabi/band/service/FileToBandStudentTranslator.kt
> +    }
그렇네요!
while loop 대신 for loop을 사용하여 더 간결한 코드로 수정하는게 좋을 거 같습니다.
수정해보겠습니다!

2024-09-02 15:02 UTC, Zepelown commented on wabi/src/main/kotlin/com/wap/wabi/student/entity/Student.java
> +}
여기선 id가 학번을 의미해서 auto increment 을 일부러 하지 않았습니다.
`save()` 하게 되면 INSERT Student (id, name) VALUES(id 입력값, name 입력값)

2024-09-02 15:14 UTC, FhRh commented on wabi/src/main/resources/application-prod.properties
> +spring.jpa.hibernate.ddl-auto=update
1. show-sql을 사용하면 해당 기능이 어떤 쿼리를 얼마나 많이 보내는지 알 수 있고, 이는 운영환경에서 로그를 확인하고 문제의 원인을 발견하는 등  유용한면이 있기에 사용하였습니다.
2. ddl-auto를 사용하면 어플리케이션 실행시, 실제 테이블에서 변경된 부분을 반영하는 DDL이 발생합니다.  하지만, 이러한 스키마 변경사항에 의해 데이터 손실 및 잠재적 오류를 야기할 수 있기 때문에 운영환경에서는 지향하는 것이 좋은 것으로 알고 있습니다.

2024-09-02 15:18 UTC, Due-IT commented on wabi/src/main/kotlin/com/wap/wabi/band/entity/BandStudent.java
> +    private String academicStatus;
재학 상태에 올수 있는 값에 대한 명세가 따로 되어있지 않아서 String으로 구현해 두었습니다..!

2024-09-02 15:19 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/event/controller/EventController.kt
> +        val response = Response.ok(data = null);
기본적으로 data에 null이 들어가도록 한다면 굳이 그럴 필요가 없겠네요! 수정하도록 하겠습니다

2024-09-02 15:22 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/band/payload/response/BandStudentData.kt
> +        }
BandStudentData를 반환하는 of 메서드는 현재 List<BandStudentData>를 반환하는 of 메서드에서만 사용되고 있습니다!
BandStudentData 자체를 반환하는 기능이 생길 수 있지 않을까 싶어 따로 private처리를 안해두었는데, 너무 앞서간 생각이었을까요?

2024-09-02 15:28 UTC, Due-IT commented on wabi/src/main/kotlin/com/wap/wabi/event/service/EventService.kt
> +		val notCheckInCount = eventStudentRepository.getEventStudentStatusCount(event, EventStudentStatus.NOT_CHECK_IN.toString())
repository의 메서드에서 Enum을 그대로 매개변수로 받아 사용하면 되는 거였군요..!
열거형과 JPA에 대한 지식이 부족했던거 같습니다 수정하겠습니다!

2024-09-02 15:30 UTC, JONG-KYEONG commented on wabi/src/main/kotlin/com/wap/wabi/event/service/EventService.kt
> +			.orElseThrow { throw RestApiException(ErrorCode.UNAUTHORIZED_CHECK_IN) }
어떤 예외가 발생했는지 확실하게 알 수 있는 부분이 장점이라고 생각합니다!

2024-09-02 15:37 UTC, JONG-KYEONG commented on wabi/src/main/kotlin/com/wap/wabi/band/payload/request/EnrollRequest.kt
> +data class EnrollRequest(val bandStudentDtos : List<BandStudentDto>)
```json
{
  "bandStudentDtos" : [
    {
       BandStudentDto 내용
    } ,
    {
       BandStudentDto 내용
    }
    ...
 ]
}
```
이렇게 보내야하는 걸로 알고 있습니다!

2024-09-02 15:41 UTC, JONG-KYEONG commented on wabi/src/main/kotlin/com/wap/wabi/band/repository/BandStudentRepository.java
> +public interface BandStudentRepository extends JpaRepository<BandStudent, Long> {
해당 부분에 어노테이션을 놓친 거 같습니다..😢

2024-09-02 15:45 UTC, JONG-KYEONG commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandEnrollService.kt
> +	}
해당 클래스 내부에서 사용하는 메서드입니다!
외부에서는 사용할 일이 없을 거 같아 private으로 처리하는게 좋아보이네요!

2024-09-02 16:05 UTC, JONG-KYEONG commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandEnrollService.kt
> +					bandStudentDto.club.toString(),
toString을 호출할 필요가 없을 거 같아서 제거하도록 하겠습니다!
null 값에 toString 을 하면 빈 문자열이 나온다고 생각하고 있었는데, 직접 실행을 해보니 null 이라는 문자열이 반환되네요.

2024-09-02 16:05 UTC, JONG-KYEONG commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandEnrollService.kt
> +		bandStudentRepository.saveAll(bandStudents)
새 엔티티 리스트인 경우 해당 엔티티들을 저장하는 INSERT 쿼리문이 리스트 크기만큼 실행되고,
기존 엔티티 리스트인 경우 UPDATE 쿼리문이 리스트 크기만큼 실행된다고 알고 있습니다!

2024-09-02 16:14 UTC, JONG-KYEONG commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandEnrollService.kt
> +		var bandStudents : MutableList<BandStudent> = mutableListOf()
var은 가변 변수, val은 불변 변수라고 알고 있습니다.
리스트 내부의 값을 수정하는 것 과는 별개인 부분인데, "리스트 내부를 수정해야하니까 가변 변수인 var로 설정해야지" 하고 이렇게 작성했던 거 같네요.

아래의 코드로 수정하는게 조금 더 좋은 방법인 거 같습니다
```
val bandStudents : MutableList<BandStudent> = mutableListOf()
```

2024-09-03 01:45 UTC, BGuga requested changes
수고하셨습니다 ~~
아직 리뷰 반영이 안된 것들이 많이 보이네요
리뷰 확인해주세요!!

2024-09-03 01:45 UTC, BGuga commented on wabi/src/main/kotlin/com/wap/wabi/band/entity/BandStudent.java
> +    private String academicStatus;
Student와 BandStudent의 필드 정보를 나눈 기준이 어떻게 되는 건가요??

2024-09-03 01:45 UTC, BGuga commented on wabi/src/main/kotlin/com/wap/wabi/student/entity/Student.java
> +}
id가 null인 Student 가 생성되지 않는 것이 좋을 것 같습니다!
엔티티를 만들 때 해당 엔티티가 어떤 제약이 있는지, 어떤 상호작용을 하는지 엔티티 내에서 정의되는 것이 좋습니다. 따라서 학번에 대한 책임을 Student가 질 수 있도록 검증을 추가하는 것이 좋아보입니다.
관련해서 Rich domain model을 검색해보면 좋을 것 같습니다.

2024-09-03 01:45 UTC, BGuga commented on wabi/src/main/kotlin/com/wap/wabi/band/service/FileToBandStudentTranslator.kt
> +) {
이 친구는 왜 Service 인가요?

2024-09-03 01:45 UTC, BGuga commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandEnrollService.kt
> +    }
@Service 메서드들에 @Transactional이 없네요
만약 추가하신다면 @Transactional이 시작된 메서드에서 파일 읽기라는 긴 동작이 포함되게 되는데 이렇게 될 경우 발생할 수 있는 문제점과 해결 방안이 있을까요??

2024-09-03 01:45 UTC, BGuga commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandEnrollService.kt
> +}
🔨

2024-09-03 05:08 UTC, JONG-KYEONG commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandEnrollService.kt
> +		return if(student.isPresent) student.get() else studentRepository.save(Student(studentId, name))
orElseGet 함수를 사용하면 간단하게 해결할 수 있겠네요!
해당 함수를 사용한 코드로 수정해보겠습니다.

2024-09-03 05:08 UTC, Zepelown commented on wabi/src/main/kotlin/com/wap/wabi/student/entity/Student.java
> +}
말씀해주신 내용 참고하여 Student 엔티티를 개선해보도록 하겠습니다 감사합니다!

2024-09-03 05:20 UTC, JONG-KYEONG commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandService.kt
> +		val band = bandRepository.findById(bandId).orElseThrow { throw RestApiException(ErrorCode.NOT_FOUND_BAND) }
예외를 반환하는 함수가 매개변수로 들어간다고 알고 있습니다!

2024-09-03 05:47 UTC, JONG-KYEONG commented on wabi/src/main/kotlin/com/wap/wabi/event/service/EventService.kt
> +		check(eventStudent.status.equals(EventStudentStatus.NOT_CHECK_IN)) { throw RestApiException(ErrorCode.ALREADY_CHECK_IN) }
`check()` 메서드는 IllegalStateException 예외를 반환하고,
해당 예외를 발생 시 500 에러 응답을 반환하는 것으로 알고 있습니다.

객체의 상태를 검증한다는 명확성과 코드의 간결성 때문에 `check()` 메서드를 사용했습니다!

2024-09-03 06:01 UTC, JONG-KYEONG commented on wabi/src/main/kotlin/com/wap/wabi/band/entity/BandStudent.java
> +    private String academicStatus;
student는 학생 고유의 정보인 이름과 학번만을 가지고, 
bandstudent는 소속마다 가지게 되는 추가적인 정보들입니다.

2024-09-03 06:07 UTC, JONG-KYEONG commented on wabi/src/main/kotlin/com/wap/wabi/band/service/FileToBandStudentTranslator.kt
> +) {
서비스보단 단순히 파일 처리와 데이터 변환의 역할을 가지는 클래스이니까 service라고 부르기가 적절하지 않은 거 같네요.
@Component 어노테이션으로 변경하는게 좋을 거 같습니다!

2024-09-03 07:21 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/band/payload/response/BandStudentData.kt
> +data class BandStudentData(
Data는 Response에 담을 데이터를 명시하는 접미사이고, Dto는 내부 로직 안에서 데이터를 전달하는 객체에 대한 접미사로 사용하였습니다..!

2024-09-03 08:49 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandEnrollService.kt
> +				bandStudentDto.academicStatus
순서가 바뀐다면 다른 속성에 값이 들어갈 우려가 있습니다!
이를 위해선 코틀린의 named arguments를 생각해볼 수 있으나 Entity는 Java이고, 이 생성자를 호출하는 BandEnrollService는 Kotlin이기에 사용이 불가하고, 같은 이유로 @Builder를 사용할 수도 없습니다.
이러한 잠재적 문제점을 해결하기 위해선 Builder를 직접 정의해서 사용해야겠네요..!

2024-09-03 09:03 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandEnrollService.kt
> +		request.bandStudentDtos.map { bandStudentDto ->
map메서드는 컬렉션에 각 요소에 대하여 변환 작업을 수행하는 메서드 입니다. `원본 컬렉션은 변경되지 않고`, `변환된 결과로 새로운 컬렉션을 생성`한다고 하네요. 
그러한 관점에서 보았을때, 변환하는 것이 아니고 새로운 엔티티를 생성해 데이터베이스에 저장하는 로직이 들어있는 것은 바람직하지 않아 보입니다. 사이드 이펙트에 의한 잠재적 문제가 생길것 같아요.
대신, forEach를 사용하는것이 더욱 적합할 수 있겠네요.

2024-09-03 10:28 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandEnrollService.kt
> +    }
호흡이 긴 메서드에서 트랜잭션이 오래동안 지속되면 리소스의 낭비와 사용자의 대기 시간 증가로 인한 사용자 경험 악화로 이어질 수 있습니다.
이러한 문제를 해결하기 위해서 대량 처리는 적당한 크기의 트랜잭션으로 나눠서 처리하는 방법이 있을것 같습니다!

2024-09-03 12:32 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandEnrollService.kt
> +}
넵 추가하였습니다!

2024-09-03 13:05 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/exception/ErrorCode.kt
> +enum class ErrorCode (val httpStatus : HttpStatus = HttpStatus.INTERNAL_SERVER_ERROR, val code: String = "", val message: String = ""){
어떤 버그가 존재할지 감이 잘 안잡히는데 혹시 힌트를 좀 주실 수 있을까요?

2024-09-03 13:17 UTC, Due-IT commented on wabi/src/main/kotlin/com/wap/wabi/event/repository/EventStudentRepository.java
> +}
1. 다음 글을 참고해주시면 감사하겠습니다.
[https://www.notion.so/JPA-47c2c410433a4c398d6bf74a1315bca8](url)
2. 즉시 제거하였습니다!
3. 코드 스타일로 인한 오류인것 같습니다 즉시 제거하였습니다!
4. 3번과 같은 이유인것 같으며 즉시 제거하였습니다!
5. JPQL문자열은 말 그대로 문자열이기 때문에 대상이 되지 않을것 같네요. 이에 대한 코드 스타일도 상의를 해보겠습니다!
6. 클래스명을 말씀하시는 거라면 주로 엔티티 이름을 접두사로 고정해서 사용해왔습니다. 하지만 리포지토리가 비대해짐에 따라 분리가 필요해진다면 그에 따른 접두사를 고려해봐야 할것 같아요.

2024-09-03 23:18 UTC, BGuga commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandEnrollService.kt
> +    }
전반적으로는 맞는 말이지만 트랜잭션을 나눠야하는 이유를 자세히 설명해주시면 좋을 것 같아요!!
설명을 조금 첨가하자면 트랜잭션은 하나의 DB 작업 단위를 의미하는 것이죠?? 
스프링은 트랜잭션 어노테이션을 달게 되면 DB 커넥션 풀에서 하나를 할당하여 트랜잭션 메서드가 끝날 때 까지 반납하게 됩니다. 이 커넥션을 오래 점유하고 있다면 커넥션이 부족해지는 경우가 생기고 다른 커넥션이 필요한 메서드는 대기하게 되겠죠 이 대기로 인해 사용자 경험이 나빠질 수 있습니다.
그래서 트랜잭션은 정말 필요한 시점에 빠르게 할당하고 반납하는 것이 좋습니다.
이 필요한 시점이란 DB의 측면이기 때문에 파일 읽기와 같은 작업은 해당하지 않습니다.

2024-09-03 23:19 UTC, BGuga commented on wabi/src/main/kotlin/com/wap/wabi/band/entity/BandStudent.java
> +    private String academicStatus;
그러면 후에 학생의 전화번호를 알기위해 BandStudent Entity에 접근해야할 것인데 이 경우는 상관 없을까요?? 
이건 기획과 관련된 것이라 여쭤봅니당

2024-09-04 09:21 UTC, JONG-KYEONG commented on wabi/src/main/kotlin/com/wap/wabi/band/entity/BandStudent.java
> +    private String academicStatus;
일단 현재 요구사항에서 어떤 소속의 학생 리스트나, 해당 소속 학생의 정보를 조회하기는 하지만, 
아무런 소속과는 상관 없이 특정 학생의 정보를 요구 하지는 않아서 이렇게 구성을 해놨습니다.

학생의 추가적인 정보들은 소속에서 필요로 하는 부가적인 학생의 정보라고 생각하고 기준을 잡았습니다.

추후 요구사항이 변경되거나 하면 변경된 요구사항에 맞게 수정하도록 하겠습니다.

2024-09-04 15:02 UTC, seokjin8678 commented on wabi/build.gradle.kts
> +    implementation("mysql:mysql-connector-java:8.0.26")
라이브러리는 잘 알아보시고 우리에게 필요한 라이브러리가 맞는지 고민하고 적용해보세요..!
(숨겨진 보안 취약점이 발견되어 라이브러리를 지우려고 할 때, 코드 상에서 해당 라이브러리에 대한 의존이 관리되지 않는다면...)

그리고 특정 라이브러리는 버전을 명시하지 않아도 스프링이 지원한다면 적절한 버전을 맞춰줍니다!
https://docs.spring.io/spring-boot/appendix/dependency-versions/coordinates.html

추가로 `runtimeOnly`, `implementation`과 같은 dependencies 구성에 대해 찾아보셔도 좋을 것 같네요!

2024-09-04 15:09 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/student/entity/Student.java
> +}
`save() 하게 되면 INSERT Student (id, name) VALUES(id 입력값, name 입력값)이 보내질 것 같습니다!`
정말 그럴까요? 직접 save 메서드를 호출해보세요! 😁

2024-09-04 15:10 UTC, seokjin8678 commented on wabi/src/main/resources/application-prod.properties
> +spring.jpa.hibernate.ddl-auto=update
운영 환경에서 `hibernate-ddl-auto`의 사용에 대해 고민을 해봐도 좋을 것 같아요.

2024-09-04 15:17 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/payload/response/BandStudentData.kt
> +        }
왠만하면 모두 private 처리를 해두는 것이 좋아요.(다른 사람이 봤을 때 혼란이 생길 수 있습니다..!)
private 처리가 되지 않았다면 해당 메서드를 의도하지 않게 사용할 수 있어요.

다만 이 경우는 간단한 매핑 메서드이니, 모두 열어줘도 좋을 것 같지만 메서드가 2개일 필요가 있을까 싶네요.
외부에서 `bandStudents.map(BandStudentData::of)` 이렇게 사용해도 좋을 것 같습니다.

2024-09-04 15:18 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/repository/BandStudentRepository.java
> +public interface BandStudentRepository extends JpaRepository<BandStudent, Long> {
사실 `@Repository` 어노테이션을 붙이지 않아도 빈으로 등록됩니다. 😂
추가로 `@Repository`을 붙이면 다른 `@Component`, `@Service`와 어떤 차이가 있는지 알아보셔도 좋을 것 같네요!

2024-09-04 15:35 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandEnrollService.kt
> +		bandStudentRepository.saveAll(bandStudents)
해당 메서드를 호출하는 일이 드물고, 사용처가 한정되니 문제는 없지만 등록할 사용자가 많다면 매우 많은 쿼리가 발생할 것 같네요..!
(쿼리가 많이 발생한다고 큰 문제는 되지 않습니다.)
다만 일반 사용자가 사용할 API에서는 이러한 문제를 고민하고 성능을 높일 방법을 고민하는게 좋아요.

2024-09-04 15:48 UTC, Zepelown commented on wabi/build.gradle.kts
> +    }
전혀 생각하지 못한 부분인데 새롭게 알고 갑니다 감사합니다!

2024-09-04 15:58 UTC, seokjin8678 approved these changes
고생하셨습니다!

해당 리뷰를 마지막으로 이번 PR에 대해 저는 리뷰 마치겠습니다!

남겨진 리뷰에 대해 답글 남겨주시면 될 것 같네요.

그리고 들여쓰기가 Tab이거나 띄어쓰기인 파일이 보이는데, 하나의 형식을 맞춰서 통일시켜주세요!

2024-09-04 15:58 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandEnrollService.kt
> +		return if(student.isPresent) student.get() else studentRepository.save(Student(studentId, name))
또한 해당 메서드의 이름과 역할이 올바르지 않은 것 같네요..!
더 적절한 이름을 고민해볼 수 있을까요?

2024-09-04 15:58 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandEnrollService.kt
> +	}
확장 함수를 사용한다면 더 읽기 좋게 바꿀 수 있을 것 같네요.
```kotlin

bandStudents.containsSameStudentIdAndClub(bandStudentDto.club, student)

private fun List<BandStudent>.containsSameStudentIdAndClub(club : String, student : Student) {
    return this.any { it.club == club && it.student == student }
}
```

2024-09-04 15:58 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandEnrollService.kt
> +	}
또한 메서드의 네이밍과 매개변수 타입의 순서도 신경써보면 좋을 것 같아요.

2024-09-04 15:58 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandEnrollService.kt
> +	}
`it.student == student`
정말 `동등`할까요?

2024-09-04 15:58 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandEnrollService.kt
> +			) bandStudents.add(bandStudent)
지금 보니 if문에 중괄호가 생략되어 있네요. 😂
짧은 경우 상관은 없으나 지금 같은 경우는 1줄이라도 넣어주세요. (팀 내 컨벤션이라면 상관 없습니다)

또한 개인의 스타일이긴 하나, 저는 가능하다면 다음과 같이 작성하는 걸 선호합니다.
```kotlin
request.bandStudentDtos.forEach { bandStudentDto ->
    val studentId = bandStudentDto.studentId
    val studentName = bandStudentDto.name
    val student = getStudent(studentId, studentName)

    val bandStudent = BandStudent(
        band,
        student,
        bandStudentDto.club,
        bandStudentDto.position,
        bandStudentDto.joinDate,
        bandStudentDto.college,
        bandStudentDto.major,
        bandStudentDto.tel,
        bandStudentDto.academicStatus
    )

    if (alreadyHasBandStudent(bandStudentDto.club.toString(), student)) {
        return@forEach
    }
    if (bandStudents.containsSameStudentIdAndClub(bandStudentDto.club.toString(), student)) {
        return@forEach
    }
    bandStudents.add(bandStudent)
}
```

2024-09-04 15:58 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandService.kt
> +		val band = bandRepository.findById(bandId).orElseThrow { throw RestApiException(ErrorCode.NOT_FOUND_BAND) }
그런데 왜 throw를 해주고 있을까요? 😂

2024-09-04 15:58 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/event/repository/EventStudentRepository.java
> +}
6. 더 정확히는 메서드명에 대해서 였습니다..!
주로 사용되는 쿼리 메서드는 다음과 같아요.

- findBy...
- deleteBy...
- existsBy...
- countBy...

2024-09-04 15:58 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/event/service/EventService.kt
> +		check(eventStudent.status.equals(EventStudentStatus.NOT_CHECK_IN)) { throw RestApiException(ErrorCode.ALREADY_CHECK_IN) }
팀 모두가 동의한 의견인가요? 그렇다면 상관 없을 것 같네요!
그리고 코틀린을 사용한다면 `equals` 메서드를 사용할 필요는 없습니다!

2024-09-04 15:58 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/exception/ErrorCode.kt
> +enum class ErrorCode (val httpStatus : HttpStatus = HttpStatus.INTERNAL_SERVER_ERROR, val code: String = "", val message: String = ""){
직접 해당 Enum을 런타임에 사용해보시고, 어떤 버그가 발생하는지 알아보세요!
```kotlin
println(ErrorCode.entries);
```

2024-09-04 15:58 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/event/service/EventService.kt
> +		eventStudentRepository.save(eventStudent)
[JPA를 사용하면 명시적으로 update 쿼리를 날리지 않는데, 어떠한 이유 때문에 그럴까요?](https://github.com/pknu-wap/WABI-BE/pull/2#discussion_r1740904811)

2024-09-04 16:08 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/payload/response/BandStudentData.kt
> +data class BandStudentData(
왠만해선 클래스 이름에 `Dto`, `Data`와 같은 네이밍이 포함되지 않는 것이 좋아요. (너무 추상적이기 때문에)
다만 팀 내에서 협의한 컨벤션이 있고, 문서화가 잘 되어 있다면 괜찮을 것 같습니다..!

2024-09-04 16:35 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/event/repository/EventStudentRepository.java
> +}
1. Entity는 Java지만, Repository는 코틀린으로 작성하지 않을 필요가 있을까요?

2024-09-06 07:02 UTC, Zepelown commented on wabi/src/main/kotlin/com/wap/wabi/qr/service/QrService.kt
> +        eventStudentRepository.save(eventStudent)
잘 모르는 부분이라 찾아봤습니다! 상태 변경 검사(Dirty Checking) 때문으로 기본적으로 JPA는 트랜잭션이 끝나는 시점에 변화가 있는 모든 엔티티 객체를 데이터베이스에 자동으로 반영합니다.
이 변화의 기준은 처음 조회한 상태입니다. 즉, 맨 처음 조회할 때 상태 그대로 데이터를 남겨두고 트랜잭션이 끝나는 시점에 남겨둔 데이터와 비교하여 다른 점이 있으면 자동으로 update 쿼리를 데이터베이스에 전달합니다!

2024-09-06 15:23 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/event/service/EventService.kt
> +		eventStudentRepository.save(eventStudent)
이는 JPA의 `영속성 컨텍스트` 때문입니다! 
 영속성 상태에 있는 엔티티들은 JPA에 의해 관리되며 `변경감지`기능에 의해 트랜잭션이 끝날때(commit)될 때, 해당 변경사항을 자동으로 DB에 적용하기 때문에 update()를 따로 명시하지 않아도 괜찮은 것으로 알고 있습니다.
그런데 해당 메서드에는 명시적으로 사용하였었네요. 이렇게 되면 불필요한 쿼리가 발생할 수 있겠어요. 즉시 지우겠습니다!

2024-09-06 15:28 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/band/payload/response/BandStudentData.kt
> +data class BandStudentData(
아하 그렇군요..! 데이터 전달을 위한 클래스의 네이밍을 다시 한번 고려해봐야겠어요.
혹시 석진님은 어떤 네이밍 규칙을 사용하시는지 알 수 있을까요??

2024-09-06 15:36 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/event/service/EventService.kt
> +		check(eventStudent.status.equals(EventStudentStatus.NOT_CHECK_IN)) { throw RestApiException(ErrorCode.ALREADY_CHECK_IN) }
check() 메서드는 주로 간단한 검증을 위해 사용되며, IllegalStateException을 반환합니다.
위 코드에선 보시다시피 이벤트에 참가하는 학생의 상태가 NOT_CHECK_IN 이어야만 체크인을 진행할 수 있기 때문에 IllegalStateException과 유사한 의미를 가진다고 생각하여 사용하게 되었습니다!

지적해주신 equals 부분은 수정하여heck() 메서드는 주로 간단한 검증을 위해 사용되며, IllegalStateException을 반환합니다.
위 코드에선 보시다시피 이벤트에 참가하는 학생의 상태가 NOT_CHECK_IN 이어야만 체크인을 진행할 수 있기 때문에 IllegalStateException과 유사한 의미를 가진다고 생각하여 사용하게 되었습니다!

지적해주신 부분에 대하여 찾아보니 코틀린의 `==` 연산자는 `equals`메서드와 같은 역할을 하는 군요! 좀 더 코틀린 스러운 코드로 작성하기 위해 해당 부분은 수정하겠습니다!

2024-09-08 11:25 UTC, seokjin8678 commented on wabi/src/main/kotlin/com/wap/wabi/band/payload/response/BandStudentData.kt
> +data class BandStudentData(
때에 따라 다르지만, Controller에서 사용하는 DTO는 `Request`, `Response`라는 접두사를 사용하고, Service에서 사용하는 DTO는 `Command`, `Result` 정도로 사용합니다.
이는 지극히 주관적이니 팀들과 같이 협의해서 일관성 있는 네이밍을 정하시면 될 것 같아요!

2024-09-09 05:41 UTC, JONG-KYEONG commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandService.kt
> +		val band = bandRepository.findById(bandId).orElseThrow { throw RestApiException(ErrorCode.NOT_FOUND_BAND) }
아? 그렇네요!

수정하도록 하겠습니다.

2024-09-10 01:52 UTC, BGuga approved these changes
수고하셨습니다~
이번 기능 개발은 훌륭히 잘 하신 것 같습니다 👍
트랜잭션 범위만 조금 더 타이트하게 잡아주시면 좋을 것 같습니다

2024-09-10 01:52 UTC, BGuga commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandEnrollService.kt
> +    }
파일 변환을 트랜잭션 범위에서 분리하는 것이 좋아보입니다!

2024-09-10 02:13 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandEnrollService.kt
> +    }
넵 해당 부분 수정하였습니다!

2024-09-10 06:33 UTC, merged