Feat/#5
pknu-wap/WABI-BE pull request #7
Opened 2024-09-18 14:36 UTC by JONG-KYEONG

##  📌 관련 이슈

- closed: #5 

## ✨ PR 세부 내용

### PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x] 기능 추가 ✨
- [ ] 기능 삭제 🔥
- [ ] 버그 수정 🐛
- [ ] 코드 형태 개선 🎨
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트 🔨

### 변경 사항

1.  그룹 생성, 수정, 삭제, 조회 기능 추가
     - POST/api/bands/create
     - DELETE/api/bands/{bandId}
     - GET/api/bands/
     - PUT/api/bands/list

2024-09-18 15:17 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandService.kt
> +    }
해당 부분처럼 admin계정을 임시로 지정하는 것은 좋은 방법인것 같은데, 여러 Service에서 중복될 우려가 있지 않을까요?

2024-09-19 01:46 UTC, FhRh requested changes
대체적으로 코드 스타일은 비슷하네요. 페어프로그래밍 한 보람이 있는것 같습니다. 
기능은 요구사항에 맞게 잘 작성된거 같은데 몇가지 궁금한 부분에 대해 질문 달아두었으니 답변 부탁드립니다!

2024-09-19 01:46 UTC, Due-IT commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandService.kt
> +        }
이 부분은 나중에 admin이 존재하는지 검증하는지 확인하고 존재하지 않다면 예외를 던지는 로직으로 변경되지 싶은데, 현재 인증보다는 임시로 만들어놓은 adminId와 같은지 비교하는 느낌이지 싶어요

2024-09-19 01:46 UTC, Due-IT commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandService.kt
> +        }
밴드에 학생이 추가되어 있다 하더라도 자유롭게 삭제될 수 있어야 하지 않을까요?

2024-09-19 01:46 UTC, Due-IT commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandService.kt
> +        }
마찬가지로, 임시 adminId만을 위해 필요한 코드가 아닐까란 느낌이 듭니다

2024-09-19 01:46 UTC, Due-IT commented on wabi/src/main/kotlin/com/wap/wabi/band/payload/response/BandsData.kt
EOL이 제거되어야 할것 같네요..!

2024-09-19 01:46 UTC, Due-IT commented on wabi/src/main/kotlin/com/wap/wabi/band/entity/Band.java
> +import com.wap.wabi.event.payload.request.EventUpdateRequest;
사용되지 않는 import가 있는거 같아요

2024-09-19 01:46 UTC, FhRh commented on wabi/src/test/kotlin/com/wap/wabi/band/service/BandEnrollServiceTest.kt
> +import java.util.*
- 사용하지 않는 import가 있습니다.
- 와일드카드로 인해 어떤 기능이 사용되었는지 정확히 알 수 없습니다.

2024-09-19 01:46 UTC, FhRh commented on wabi/src/test/kotlin/com/wap/wabi/band/service/BandEnrollServiceTest.kt
> +        )
studentId를 제외하고는 이후에 재사용되지 않는 변수들인데 분리할 필요가 있을까요?

2024-09-19 01:46 UTC, FhRh commented on wabi/src/test/kotlin/com/wap/wabi/band/service/BandEnrollServiceTest.kt
> +        bandStudentDtos.add(bandStudentDto)
```sugestion
val bandStudentDtos: MutableList<BandStudentDto> = mutableListOf(bandStudentDto)
```
위와 같이 더 간결하게 쓸 수도 있을것 같아요

2024-09-19 01:46 UTC, FhRh commented on wabi/src/test/kotlin/com/wap/wabi/band/service/BandEnrollServiceTest.kt
> +        }
예외가 발생하지 않는 것만으로 메서드의 적합성을 판단하는데 충분할까요?

2024-09-19 01:46 UTC, FhRh commented on wabi/src/test/kotlin/com/wap/wabi/band/service/BandServiceTest.kt
- 많은 테스트 코드가 repository에 대해 올바르지 않은 입력값이나 반환값 발생시 예외를 체크하는 방향으로 작성되어 있는것 같은데 올바르게 동작하는지에 대한 테스트는 없어도 괜찮을까요? 
- 테스트 코드는 유지보수 및 변경에 따른 에러를 발견함에 있어서 디버깅 비용을 절감하기도 하지만, 명세서로써도 중요하게 작용한다고 생각합니다. 해당 테스트 클래스는 그런 측면에서 좋은 명세서가 될 수 있을까요? 
- 또한, 커스텀한 예외가 잘 동작하는지에 대해 테스트하고 있진 않은걸까요?

2024-09-19 06:22 UTC, JONG-KYEONG commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandService.kt
> +        }
기능명세서에서 아래와 같이 명세되었기에 해당 요구에 맞게 구현하였습니다!

![image](https://github.com/user-attachments/assets/3307ca9f-2b60-418e-a0cd-4d805fb1ce76)

2024-09-19 06:23 UTC, JONG-KYEONG commented on wabi/src/main/kotlin/com/wap/wabi/band/entity/Band.java
> +import com.wap.wabi.event.payload.request.EventUpdateRequest;
확인 후 제거하도록 하겠습니다!

2024-09-19 07:45 UTC, JONG-KYEONG commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandService.kt
> +        }
로그인 부분이 구현이 완료된다면 adminId가 아닌 jwt 토큰을 사용한 검증이 사용될 거 같아서, 임증 보다는 임시로 만들어놓은 adminId와 같은지만 판단하게 작성해놓았습니다!

2024-09-19 07:46 UTC, JONG-KYEONG commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandService.kt
> +        }
로그인 부분이 구현 완료된다면, 검증 코드를 추가하도록 하겠습니다.

2024-09-19 07:46 UTC, JONG-KYEONG commented on wabi/src/main/kotlin/com/wap/wabi/band/payload/response/BandsData.kt
EOL 추가 하도록 하겠습니다!

2024-09-19 07:52 UTC, JONG-KYEONG commented on wabi/src/test/kotlin/com/wap/wabi/band/service/BandEnrollServiceTest.kt
> +import java.util.*
사용하지 않는 improt 삭제 및 와일드 카드 대신 사용하는 기능만 import 하도록 수정하였습니다 :)

2024-09-19 07:53 UTC, JONG-KYEONG commented on wabi/src/test/kotlin/com/wap/wabi/band/service/BandEnrollServiceTest.kt
> +        )
재사용성이나 명확성을 위해 분리해두었습니다!
하지만 지금 당장 사용하지 않는다면 분리할 필요는 없어보이네요!

2024-09-19 07:54 UTC, JONG-KYEONG commented on wabi/src/test/kotlin/com/wap/wabi/band/service/BandEnrollServiceTest.kt
> +        bandStudentDtos.add(bandStudentDto)
좋은 방법이네요!
수정하겠습니다.

2024-09-19 07:57 UTC, JONG-KYEONG commented on wabi/src/test/kotlin/com/wap/wabi/band/service/BandEnrollServiceTest.kt
> +        }
해당 메소드에서 예외가 발생하지 않지만 제대로 작동하지 않을 확률이 있습니다.

이 부분에 있어서 팀원들과 회의를 통해 조금 더 나은 방법으로 테스트 코드를 작성 해야할 거 같습니다.

2024-09-20 05:29 UTC, JONG-KYEONG commented on wabi/src/test/kotlin/com/wap/wabi/band/service/BandServiceTest.kt
아무래도 테스트 코드 작성이 처음 인지라 어떤 방법이 최적의 방법인지 고민 중에 있습니다.
이 부분에 있어서 추후 추가적인 회의와 리팩토링이 필요할 거 같습니다!

2024-09-20 05:37 UTC, JONG-KYEONG commented on wabi/src/main/kotlin/com/wap/wabi/band/service/BandService.kt
> +    }
동의하는 부분입니다.
공통으로 사용할 수 있는 클래스를 생성하는 것도 좋은 방법일 거 같네요.

2024-09-20 05:47 UTC, FhRh approved these changes
고생 많으셨습니다! 기능상의 문제도 없고 스타일은 맞추었지만, 더욱 최적화된 테스트 방식에 대해선 다함께 이야기할 필요성이 있어 보이네요 :)

2024-09-20 05:53 UTC, merged