Feat/#4
pknu-wap/WABI-BE pull request #8
Opened 2024-09-18 15:07 UTC by FhRh

##  📌 관련 이슈

- closed: #4 

## ✨ PR 세부 내용

- Event 및 Fixture 관련 부분 위주로 봐주시면 감사하겠습니다.

## ⌛ 소요 시간

2024-09-19 07:43 UTC, JONG-KYEONG requested changes
우선 개발 하신다고 수고 많으셨습니다!
기능 부분은 요구사항에 맞게 개발된 거 같습니다. 
궁금한 부분이나 수정이 필요할 거 같은 부분 코멘트 남겼으니 확인 부탁드립니다 :)

2024-09-19 07:43 UTC, JONG-KYEONG commented on wabi/src/main/kotlin/com/wap/wabi/event/service/EventService.kt
> +        val event = eventRepository.findById(eventId).orElseThrow { throw RestApiException(ErrorCode.NOT_FOUND_EVENT) }
orElseThrow 함수 내에 throw를 제거하는게 맞지 않을까요?

2024-09-19 07:43 UTC, JONG-KYEONG commented on wabi/src/test/kotlin/com/wap/wabi/event/service/EventServiceTest.kt
> +        )
eventId를 제외하고는 이후에 재사용되지 않는 변수들인데 분리하신 이유가 따로 있을까요?

2024-09-19 07:43 UTC, JONG-KYEONG commented on wabi/src/main/kotlin/com/wap/wabi/event/service/EventService.kt
> +    }
eventStudents.size를 필요로 하는 메소드가 프로덕션 코드엔 없는 거 같은데, 
해당 함수에서 이것을 리턴 하는 이유가 있을까요?

2024-09-19 07:43 UTC, JONG-KYEONG commented on wabi/src/test/kotlin/com/wap/wabi/common/TestConstants.kt
> +}
EOL 추가해주세요!

2024-09-19 07:43 UTC, JONG-KYEONG commented on wabi/src/test/kotlin/com/wap/wabi/event/fixture/EventStudentFixture.kt
> +}
EOL 추가해주세요 :)

2024-09-19 07:43 UTC, JONG-KYEONG commented on wabi/src/test/kotlin/com/wap/wabi/event/service/EventServiceTest.kt
> +        verify(eventRepository, times(1)).delete(event)
해당 테스트가 삭제가 성공적으로 이루어졌는지에 대한 검증을 한다고 볼 수 있을까요?

2024-09-20 05:26 UTC, JONG-KYEONG commented on wabi/src/main/kotlin/com/wap/wabi/event/service/EventService.kt
> +            .orElseThrow { throw RestApiException(ErrorCode.UNAUTHORIZED_CHECK_IN) }
해당 부분도 다 throw가 제거되어야 할 거 같네요!

2024-09-20 05:28 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/event/service/EventService.kt
> +        val event = eventRepository.findById(eventId).orElseThrow { throw RestApiException(ErrorCode.NOT_FOUND_EVENT) }
동의 합니다. 수정하였습니다!

2024-09-20 05:31 UTC, FhRh commented on wabi/src/test/kotlin/com/wap/wabi/event/service/EventServiceTest.kt
> +        )
아니요. 굳이 재사용되거나 중요한 의미를 가지는 변수가 아니면 분리할 이유가 딱히 없어 보이네요!

2024-09-20 05:40 UTC, FhRh reviewed
관련하여 답변 달아두었습니다! 재확인 부탁드릴게요 :)

2024-09-20 05:40 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/event/service/EventService.kt
> +            .orElseThrow { throw RestApiException(ErrorCode.UNAUTHORIZED_CHECK_IN) }
넵 제거 하였습니다!

2024-09-20 05:40 UTC, FhRh commented on wabi/src/test/kotlin/com/wap/wabi/event/service/EventServiceTest.kt
> +        verify(eventRepository, times(1)).delete(event)
eventService.deleteEvent()가 성공적으로 로직을 처리하였는지는 단위 테스트 관점에서 eventRepository.delete()를 호출했다는 것에서 검증이 끝났다고 생각합니다. 그 이후에 repository가 정말 객체를 삭제하였는지는 통합테스트 또는 repository에 대한 단위테스트로 검증해야 할것 같아요.

2024-09-20 05:40 UTC, FhRh commented on wabi/src/test/kotlin/com/wap/wabi/event/fixture/EventStudentFixture.kt
> +}
넵 추가 하였습니다!

2024-09-20 05:40 UTC, FhRh commented on wabi/src/test/kotlin/com/wap/wabi/common/TestConstants.kt
> +}
추가하였습니다 :)

2024-09-20 05:40 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/event/service/EventService.kt
> +    }
save에 대해 테스트를 하는 두 가지 방법이 있다고 생각합니다.
- 예외가 발생하였는지 확인하는 방법
- 메서드를 호출하였는지 확인하는 방법
- 메서드의 반환값을 확인하는 방법

여기서 총결과값을 확인하는 방법은 위의 두가지 방법을 모두 검증할 수 있다고 생각하여 위와 같이 구현하였습니다!
사실상 적은 비용과 프로덕션 코드에 문제가 발생하지 않는 선에서 테스트를 편리하게 하기 위해서라고 볼 수 있을것 같아요 :)

2024-09-20 05:47 UTC, JONG-KYEONG commented on wabi/src/main/kotlin/com/wap/wabi/event/service/EventService.kt
> +    }
해당 부분은 추가적으로 회의를 통해 팀원들과 통일하면 좋을 거 같네요 :)

2024-09-20 05:48 UTC, JONG-KYEONG approved these changes

2024-09-20 05:48 UTC, merged