Feat/#6
pknu-wap/WABI-BE pull request #9
Opened 2024-09-18 17:13 UTC by Zepelown

##  📌 관련 이슈

- closed: #6 

## ✨ PR 세부 내용
### 관리자 테이블
![image](https://github.com/user-attachments/assets/8e1f9de6-cd85-430d-97f6-34d10affe7f5)

#### 관리자 이름 조건
1. 최소 4자 이상, 10자 이하
2. 알파벳 소문자(a~z), 숫자(0~9) 로만 구성

#### 관리자 비밀번호 조건
1. 최소 8자 이상, 15자 이하
2. 알파벳 대소문자(a~z, A~Z), 숫자(0~9), 특수 문자(~!@#) 중 하나로 구성
3. 특수문자는 반드시 하나 이상 있어야 한다

#### 관리자 Role(권한, 등급)
```
public enum AdminRole {
    USER,
    SUPERVISOR,
}

```

#### 관리자 상태
```
public enum AdminStatus {
    ACTIVE,
    FREEZE
}
```
### 패키지 구조
![image](https://github.com/user-attachments/assets/2412c000-e8d9-4cb5-9fc3-2f0cac7e9d37)

### 추가된 라이브러리
```
    implementation ("org.springframework.boot:spring-boot-starter-security")
    implementation ("io.jsonwebtoken:jjwt-api:0.11.5")
    implementation ("io.jsonwebtoken:jjwt-impl:0.11.5")
    implementation ("io.jsonwebtoken:jjwt-jackson:0.11.5")
```
#### Spring Security
서버에 인증과 권한을 통해 접근에 제한을 두기 위해 추가한 라이브러리
#### JWT (JSON Web Token)
Spring Security에서 필요한 인증을 진행하기 위해 사용한 라이브러리
쿠키, 세션 방식과 다르게 http 원래 의도와 맞는 stateless 방식을 사용하여 채택하였습니다.

2024-09-20 06:15 UTC, JONG-KYEONG requested changes
개발하신다고 고생하셨습니다!
깔끔하니 좋네요 :)

코드 스타일이 통일되지 않는 파일과 사용하지 않는 import가 남아있는 파일이 꽤 보입니다!
해당 부분 수정해주시면 될 거 같습니다

2024-09-20 06:15 UTC, JONG-KYEONG commented on wabi/src/main/kotlin/com/wap/wabi/auth/admin/util/AdminValidator.kt
> +}
Rich Domain Model을 사용하여 도메인 안에 검증 로직을 넣지 않고, 
따로 클래스를 만들어서 사용하신 이유가 있을까요?

2024-09-20 06:15 UTC, JONG-KYEONG commented on wabi/src/test/kotlin/com/wap/wabi/admin/service/AdminServiceTest.kt
> +}
EOL 추가해주세요 :)

2024-09-20 06:15 UTC, JONG-KYEONG commented on wabi/src/test/kotlin/com/wap/wabi/admin/service/AdminServiceTest.kt
> +import org.junit.jupiter.api.BeforeEach
사용하지 않는 import가 있는 거 같아요!

2024-09-20 06:15 UTC, JONG-KYEONG commented on wabi/src/main/kotlin/com/wap/wabi/auth/jwt/JwtTokenProvider.kt
> +import kotlin.collections.HashMap
여기도 사용하지 않는 import가 있는 거 같습니다 :)

2024-09-20 07:04 UTC, FhRh requested changes
인증/인가에 관련해서 처음하신거 같은데 대단히 수고하셨습니다!
리뷰 달아두었으니 확인하시고 재요청 부탁드립니다 :)

2024-09-20 07:04 UTC, Due-IT commented on wabi/src/main/kotlin/com/wap/wabi/exception/ErrorCode.kt
> +    EXIST_ADMIN(HttpStatus.BAD_REQUEST, "600-2","이미 존재하는 어드민입니다.")
600은 Event와 관련된 ErrorCode를 모아둔 것으로 보이는데, 600번대를 사용해도 괜찮을까요?

2024-09-20 07:04 UTC, Due-IT commented on wabi/src/main/kotlin/com/wap/wabi/exception/ErrorCode.kt
> +    BAD_REQUEST_ADMIN_NAME(HttpStatus.BAD_REQUEST,"400-33","이름이 형식에 맞지 않습니다."),
개인적으로 인증/인가에 관한 ErrorCode그룹을 따로 만드는 것이 좋아보이는데 어떻게 생각하시나요??

2024-09-20 07:04 UTC, Due-IT commented on wabi/src/main/kotlin/com/wap/wabi/auth/admin/payload/request/AdminRegisterRequest.kt
> +            .password(encoder.encode(this.password))
해당 부분에서 encoder는 어떤 방식으로 암호화하나요?

2024-09-20 07:04 UTC, Due-IT commented on wabi/src/main/kotlin/com/wap/wabi/auth/admin/entity/Enum/AdminRole.java
role 어떤 이유로 두 가지로 나뉘었나요?

2024-09-20 07:04 UTC, Due-IT commented on wabi/src/main/kotlin/com/wap/wabi/auth/admin/entity/Enum/AdminStatus.java
FREEZE는 어디에서도 사용되지 않고 있네요. 어떨 때에 사용될 것으로 예상하시나요?

2024-09-20 07:04 UTC, Due-IT commented on wabi/src/main/kotlin/com/wap/wabi/auth/admin/payload/request/AdminLoginRequest.kt
> +    val password: String
로그인 시에 email이 아닌 name을 전달받는 이유가 무엇인가요?

2024-09-20 07:04 UTC, Due-IT commented on wabi/src/main/kotlin/com/wap/wabi/auth/admin/entity/Admin.java
> +    private AdminStatus status;
현재 로직상, name과 password로 로그인을 하게 되는데, Entity 정보상에서 name은 고유해야 함이 드러나지 않고, AdminValidator에서 확인 된다는게 조금 아쉬운거 같아요 ..!

2024-09-20 07:04 UTC, Due-IT commented on wabi/src/main/kotlin/com/wap/wabi/auth/admin/repository/AdminRepository.java
> +    Optional<Admin> findAdminByName(@Param("name") String name);
해당 부분은 @Query를 사용하지 않고 `Declared Query`로 충분히 구현 가능해 보여요!
[https://docs.spring.io/spring-data/jpa/reference/jpa/query-methods.html#jpa.query-methods.declared-queries](url)

2024-09-20 07:04 UTC, Due-IT commented on wabi/src/main/kotlin/com/wap/wabi/auth/config/SecurityConfig.kt
> +import org.springframework.security.web.authentication.www.BasicAuthenticationFilter
사용되지 않는 import가 있네요!

2024-09-20 07:04 UTC, Due-IT commented on wabi/src/main/kotlin/com/wap/wabi/auth/config/SecurityConfig.kt
> +            }
해당 부분은 어떤 설정인가요?

2024-09-20 07:04 UTC, Due-IT commented on wabi/src/main/kotlin/com/wap/wabi/common/utils/StringUtils.kt
> +        @JvmStatic
이건 어떤 어노테이션인가요?

2024-09-20 07:52 UTC, Zepelown commented on wabi/src/main/kotlin/com/wap/wabi/auth/admin/entity/Enum/AdminRole.java
차후 확장성을 고려하여 개발자를 위한 Role인 Supervisior를 추가하였습니다.

2024-09-20 08:17 UTC, Zepelown commented on wabi/src/main/kotlin/com/wap/wabi/common/utils/StringUtils.kt
> +        @JvmStatic
코틀린 object를 자바에서 사용하기 위해 필요한 어노테이션입니다.
기존에 이름 및 비밀번호 validate를 엔티티(자바 파일)에서 진행했었기 때문에 넣어뒀던 어노테이션인데 Validator로 분리해놓고 지우는 걸 까먹었네요
수정했습니다

2024-09-20 08:33 UTC, Zepelown commented on wabi/src/main/kotlin/com/wap/wabi/auth/config/SecurityConfig.kt
> +            }
iframe 태그를 막는 기능을 비활성화하는 기능입니다.
지금 보니 필요없는 코드일 것 같아 제거하였습니다.

2024-09-20 08:38 UTC, Zepelown commented on wabi/src/main/kotlin/com/wap/wabi/auth/admin/util/AdminValidator.kt
> +}
Admin 엔티티에 비밀번호 암호화, 검증 로직이 같이 들어가는 상황이 발생하여 너무 커져서 Validator로 분리하는 방식으로 진행하였습니다.

2024-09-20 08:47 UTC, Zepelown commented on wabi/src/main/kotlin/com/wap/wabi/exception/ErrorCode.kt
> +    EXIST_ADMIN(HttpStatus.BAD_REQUEST, "600-2","이미 존재하는 어드민입니다.")
다른 번호를 부여하도록 하겠습니다!

2024-09-26 19:25 UTC, Zepelown commented on wabi/src/main/kotlin/com/wap/wabi/exception/ErrorCode.kt
> +    BAD_REQUEST_ADMIN_NAME(HttpStatus.BAD_REQUEST,"400-33","이름이 형식에 맞지 않습니다."),
저도 좋다고 생각하여 에러 코드를 분리하였습니다!

2024-09-26 19:34 UTC, Zepelown commented on wabi/src/main/kotlin/com/wap/wabi/auth/admin/payload/request/AdminRegisterRequest.kt
> +            .password(encoder.encode(this.password))
해시 함수를 이용한 salt 방식의 암호화입니다. BCryptPasswordEncoder 객체를 사용하여 암호화를 진행합니다.
encode해서 나온 결과물엔 해쉬값과 암호화된 비밀번호를 가지고 있기 때문에 후에 match를 사용하여 비교할 수 있습니다.

2024-09-26 19:35 UTC, Zepelown commented on wabi/src/main/kotlin/com/wap/wabi/auth/admin/entity/Enum/AdminStatus.java
차후 특정 계정을 정지할 필요가 있을 때, 사용할 것 같습니다

2024-09-26 19:36 UTC, Zepelown commented on wabi/src/main/kotlin/com/wap/wabi/auth/admin/payload/request/AdminLoginRequest.kt
> +    val password: String
아이디, 비밀번호 형식으로 회원 관리를 하고 싶었기 때문입니다. 지금 생각해보면 이메일로 해도 나쁘지 않을 것 같습니다

2024-09-26 19:38 UTC, Zepelown commented on wabi/src/main/kotlin/com/wap/wabi/auth/admin/entity/Admin.java
> +    private AdminStatus status;
@Column(unique = true)
위 어노테이션을 통해 명시적으로 처리하였습니다

2024-09-26 19:42 UTC, Zepelown commented on wabi/src/main/kotlin/com/wap/wabi/auth/admin/repository/AdminRepository.java
> +    Optional<Admin> findAdminByName(@Param("name") String name);
수정해보았습니다!

2024-09-28 02:57 UTC, JONG-KYEONG commented
AdminRepository, SecurityConfig에 아직 사용하지 않는 import가 남아있는 거 같습니다!
해당 부분만 수정해주시고 머지하시면 될 거 같습니다 :)

2024-09-28 02:57 UTC, JONG-KYEONG approved these changes

2024-09-30 05:19 UTC, FhRh approved these changes
저번에 작성했던 리뷰에 대해 답변도 잘 달아주셨고, 수정도 잘 해주신것 같습니다!
몇가지 추가 질문에 대한 답변은 선택사항이시고, EOL만 제거해서 합치면 될것 같아요.
고생하셨습니다 :)

2024-09-30 05:19 UTC, FhRh commented on wabi/build.gradle.kts
> +}
아직 EOL이 추가 되지 않은 부분이 있는것 같아요!

2024-09-30 05:19 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/auth/admin/entity/Admin.java
> +    }
이 함수는 어떤 함수인가요?

2024-09-30 05:19 UTC, FhRh commented on wabi/src/main/kotlin/com/wap/wabi/auth/admin/entity/Admin.java
> +    }
모두 고정된 값을 반환하고 있는데 이후에 사용될 계획이 있을까요?

2024-09-30 06:11 UTC, Zepelown commented on wabi/build.gradle.kts
> +}
수정했습니다!

2024-09-30 06:43 UTC, Zepelown commented on wabi/src/main/kotlin/com/wap/wabi/auth/admin/entity/Admin.java
> +    }
Spring Security의 UserDetails 인터페이스 구현에 필요한 메소드로 차후 유저 권한에 대한 자세한 명세가 생기면 권한 목록에 대한 정보를 조회하는 메소드입니다.

2024-09-30 06:46 UTC, Zepelown commented on wabi/src/main/kotlin/com/wap/wabi/auth/admin/entity/Admin.java
> +    }
위의 getAuthorities() 처럼 UserDetails 객체 구현에 필요한 메소드들로 이것 또한 향후 유저 관련 기능에 대해 명세가 구체화 되면 수정할 계획입니다. 아마 계정 정지 및 권한 분리에 사용될 것 같습니다.

2024-09-30 06:49 UTC, merged